name: Flutter Android CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies (Flutter module)
        run: flutter pub get
        working-directory: common

      - name: Make Gradle executable
        run: chmod +x gradlew
        working-directory: android

      # Debug APK via Gradle
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: android

      # Release APK via Gradle
      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            android/app/build/outputs/**/*.apk 