name: Flutter Android CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Debug APK
      - name: Build Debug APK
        run: flutter build apk --debug

      # Release APK
      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/*.apk 