name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install FVM
        run: dart pub global activate fvm

      - name: Add FVM to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Fix script permissions
        run: |
          chmod +x scripts/pigeon.py
          chmod +x android/gradlew

      - name: Install Flutter via FVM
        run: fvm install

      - name: Flutter version (via FVM)
        run: fvm flutter --version | cat

      - name: Flutter pub get
        run: fvm flutter pub get | cat

      - name: Build APK (family)
        run: make build-android-family-debug | cat

      - name: Build APK (six)
        run: make build-android-six-debug | cat

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            android/app/build/outputs/**/*.apk 