name: iOS Debug (manual)

on:
  workflow_dispatch:

jobs:
  ios-debug:
    name: Build common iOS framework (debug)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install FVM
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      - name: Set up Flutter via FVM
        working-directory: common
        run: |
          fvm install
          fvm use
          fvm flutter --version | cat

      - name: Install iOS deps
        working-directory: ios
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch
          gem install cocoapods --user-install
          pod install --repo-update | cat

      - name: Build iOS framework (debug)
        working-directory: common
        run: |
          ./scripts/build.for.ios.sh debug | cat

      - name: Upload iOS framework
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: common/build/ios-framework 